name: Rust

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  CI: 1
  CARGO_INCREMENTAL: 1

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              curl file gcc g++ git make openssh-client \
              autoconf automake cmake libtool libcurl4-openssl-dev libssl-dev llvm\
              libelf-dev libdw-dev binutils-dev zlib1g-dev libiberty-dev wget \
              xz-utils pkg-config python libclang-6.0-dev clang ocl-icd-opencl-dev libgflags-dev libhwloc-dev
      - name: Checkout Sources
        uses: actions/checkout@v2
      - name: Install Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Rust Cache
        uses: Swatinem/rust-cache@v1.3.0
      - name: Cargo Check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: Make Test-All
        run: |
          export RUST_TEST_THREADS=$(nproc)
          git submodule update --init
          cargo test --release --all --exclude serialization_tests --exclude conformance_tests --exclude forest_message --exclude forest_crypto -- --test-threads=$(RUST_TEST_THREADS)
          cargo test --release -p forest_crypto --features blst --no-default-features -- --test-threads=$(RUST_TEST_THREADS)
          cargo test --release -p forest_crypto --features pairing --no-default-features -- --test-threads=$(RUST_TEST_THREADS)
          cargo test --release -p forest_message --features blst --no-default-features -- --test-threads=$(RUST_TEST_THREADS)
          cargo test --release -p forest_message --features pairing --no-default-features -- --test-threads=$(RUST_TEST_THREADS)
          cargo test --release --manifest-path=tests/serialization_tests/Cargo.toml --features "submodule_tests" -- --test-threads=$(RUST_TEST_THREADS)
          cargo test --release --manifest-path=tests/conformance_tests/Cargo.toml --features "submodule_tests" -- --nocapture --test-threads=$(RUST_TEST_THREADS)

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        rv: [1.57.0, stable]
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - name: Checkout Sources
        uses: actions/checkout@v2
      - name: Install Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rv }}
          override: true
      - name: Rust Cache
        uses: Swatinem/rust-cache@v1.3.0
      - name: Cargo Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --profile dev
